import { Router, type IRouter } from "express";
import healthRouter from "./health.js";
import authRouter from "./auth.js";
import usersRouter from "./users.js";
import agentsRouter from "./agents.js";
import voicesRouter from "./voices.js";
import campaignsRouter from "./campaigns.js";
import numbersRouter from "./numbers.js";
import leadsRouter from "./leads.js";
import leadListsRouter from "./leadLists.js";
import callsRouter from "./calls.js";
import agentStatusRouter from "./agentStatus.js";
import manualCallRouter from "./manualCall.js";
import callLogsRouter from "./callLogs.js";
import dashboardRouter from "./dashboard.js";
import humanAgentsRouter from "./humanAgents.js";
import smsRouter from "./sms.js";
import webhooksRouter from "./webhooks.js";
import exportRouter from "./export.js";
import callbacksRouter from "./callbacks.js";
import audioRouter from "./audio.js";
import dncRouter from "./dnc.js";
import queuesRouter from "./queues.js";
import llmRouter from "./llm.js";
import optimizerRouter from "./optimizer.js";
import scriptsRouter from "./scripts.js";
import clusterRouter from "./cluster.js";
import vapiRouter from "./vapi.js";
import uploadsRouter from "./uploads.js";
import { globalErrorHandler } from "../lib/errors.js";
import type { Request, Response, NextFunction } from "express";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(humanAgentsRouter);
router.use(agentsRouter);
router.use(voicesRouter);
router.use(campaignsRouter);
router.use(numbersRouter);
router.use(leadsRouter);
router.use(leadListsRouter);
router.use(callsRouter);
router.use(agentStatusRouter);
router.use(manualCallRouter);
router.use(callLogsRouter);
router.use(dashboardRouter);
router.use(smsRouter);
router.use(webhooksRouter);
router.use(exportRouter);
router.use(callbacksRouter);
router.use(audioRouter);
router.use(dncRouter);
router.use(queuesRouter);
router.use(llmRouter);
router.use(optimizerRouter);
router.use(scriptsRouter);
router.use(clusterRouter);
router.use(vapiRouter);
router.use(uploadsRouter);

router.use((err: Error, req: Request, res: Response, next: NextFunction) => globalErrorHandler(err, req, res, next));

export default router;
