#!/usr/bin/env bash
# SHIVANSH LB health monitor
# ---------------------------------------------------------------
# Polls every node listed in deploy/lb/vps-registry.json and rewrites
# /etc/nginx/conf.d/shivansh-upstream.conf so unhealthy nodes are
# marked `down`. Validates the new file with `nginx -t` BEFORE reloading,
# so a bad rewrite can never take the LB offline.
#
# Run under PM2 or systemd:
#   pm2 start deploy/lb/health-monitor.sh --name shivansh-lb-monitor --interpreter bash
#   pm2 save
#
# Or as a systemd unit (recommended on the LB box):
#   sudo cp deploy/lb/shivansh-lb-monitor.service /etc/systemd/system/
#   sudo systemctl daemon-reload && sudo systemctl enable --now shivansh-lb-monitor
# ---------------------------------------------------------------
set -euo pipefail

REGISTRY="${REGISTRY:-/opt/shivansh/deploy/lb/vps-registry.json}"
UPSTREAM_FILE="${UPSTREAM_FILE:-/etc/nginx/conf.d/shivansh-upstream.conf}"
STATE_DIR="${STATE_DIR:-/var/lib/shivansh-lb}"
LOG_TAG="[lb-monitor]"

mkdir -p "$STATE_DIR"

log() { echo "$LOG_TAG $(date -Iseconds) $*"; }

require() {
  command -v "$1" >/dev/null 2>&1 || { log "FATAL: $1 not installed"; exit 1; }
}
require jq
require curl
require nginx

# Load settings
INTERVAL=$(jq -r '.settings.check_interval_seconds // 10' "$REGISTRY")
FAIL_THRESHOLD=$(jq -r '.settings.fail_threshold // 3' "$REGISTRY")
RECOVER_THRESHOLD=$(jq -r '.settings.recover_threshold // 2' "$REGISTRY")
TIMEOUT=$(jq -r '.settings.request_timeout_seconds // 5' "$REGISTRY")
MIN_POOL=$(jq -r '.settings.min_pool_size // 1' "$REGISTRY")
HEALTH_PATH=$(jq -r '.settings.health_path // "/api/health"' "$REGISTRY")

declare -A FAIL_COUNT
declare -A OK_COUNT
declare -A STATUS  # "up" | "down"

# Initialize all enabled nodes as "up" — let the first cycle correct it
while read -r id; do
  FAIL_COUNT[$id]=0
  OK_COUNT[$id]=0
  STATUS[$id]="up"
done < <(jq -r '.pool[] | select(.enabled == true) | .id' "$REGISTRY")

write_upstream() {
  local tmp="$STATE_DIR/upstream.new"
  {
    echo "# Auto-generated by health-monitor.sh @ $(date -Iseconds)"
    echo "# DO NOT EDIT — run deploy/lb/health-monitor.sh instead"
    echo "upstream shivansh_upstream {"
    echo "    ip_hash;"
    while IFS=$'\t' read -r id host port weight; do
      local marker=""
      [[ "${STATUS[$id]:-up}" == "down" ]] && marker=" down"
      echo "    server ${host}:${port} weight=${weight} max_fails=3 fail_timeout=15s${marker};"
    done < <(jq -r '.pool[] | select(.enabled == true) | [.id, .host, .port, (.weight // 1)] | @tsv' "$REGISTRY")
    echo "    keepalive 32;"
    echo "}"
  } > "$tmp"

  # Diff — skip reload if no change
  if [[ -f "$UPSTREAM_FILE" ]] && cmp -s "$tmp" "$UPSTREAM_FILE"; then
    rm -f "$tmp"
    return 0
  fi

  # Failsafe — back up current, install new, validate, rollback on failure
  local backup="$STATE_DIR/upstream.backup"
  [[ -f "$UPSTREAM_FILE" ]] && cp "$UPSTREAM_FILE" "$backup"
  cp "$tmp" "$UPSTREAM_FILE"
  rm -f "$tmp"

  if nginx -t >/dev/null 2>&1; then
    if nginx -s reload >/dev/null 2>&1; then
      log "Upstream rewritten and nginx reloaded"
      return 0
    else
      log "ERROR: nginx reload failed — rolling back"
    fi
  else
    log "ERROR: nginx -t rejected new upstream — rolling back"
  fi

  if [[ -f "$backup" ]]; then
    cp "$backup" "$UPSTREAM_FILE"
    nginx -s reload >/dev/null 2>&1 || true
  fi
  return 1
}

# Count enabled nodes that are currently "up" — never let pool go below MIN_POOL
healthy_count() {
  local n=0
  for s in "${STATUS[@]}"; do
    [[ "$s" == "up" ]] && n=$((n+1))
  done
  echo "$n"
}

main_loop() {
  while true; do
    # Snapshot enabled nodes
    while IFS=$'\t' read -r id host port; do
      url="http://${host}:${port}${HEALTH_PATH}"
      if curl -fsS --max-time "$TIMEOUT" "$url" >/dev/null 2>&1; then
        OK_COUNT[$id]=$(( ${OK_COUNT[$id]:-0} + 1 ))
        FAIL_COUNT[$id]=0
        if [[ "${STATUS[$id]:-up}" == "down" && ${OK_COUNT[$id]} -ge $RECOVER_THRESHOLD ]]; then
          log "RECOVERED: $id ($host:$port)"
          STATUS[$id]="up"
        fi
      else
        FAIL_COUNT[$id]=$(( ${FAIL_COUNT[$id]:-0} + 1 ))
        OK_COUNT[$id]=0
        if [[ "${STATUS[$id]:-up}" == "up" && ${FAIL_COUNT[$id]} -ge $FAIL_THRESHOLD ]]; then
          # Refuse to mark down if we'd drop below MIN_POOL
          local healthy
          healthy=$(healthy_count)
          if [[ $healthy -le $MIN_POOL ]]; then
            log "WARN: $id is unhealthy but pool would drop below MIN_POOL=$MIN_POOL — keeping in rotation"
          else
            log "DOWN: $id ($host:$port) — failed $FAIL_THRESHOLD checks"
            STATUS[$id]="down"
          fi
        fi
      fi
    done < <(jq -r '.pool[] | select(.enabled == true) | [.id, .host, .port] | @tsv' "$REGISTRY")

    # Persist current state for /api/admin/cluster/status
    {
      echo -n '{"updated_at":"'"$(date -Iseconds)"'","nodes":['
      first=1
      for id in "${!STATUS[@]}"; do
        [[ $first -eq 0 ]] && echo -n ','
        first=0
        echo -n "{\"id\":\"$id\",\"status\":\"${STATUS[$id]}\",\"fail_count\":${FAIL_COUNT[$id]:-0},\"ok_count\":${OK_COUNT[$id]:-0}}"
      done
      echo ']}'
    } > "$STATE_DIR/status.json.tmp" && mv "$STATE_DIR/status.json.tmp" "$STATE_DIR/status.json"

    write_upstream || true

    sleep "$INTERVAL"
  done
}

log "Starting LB monitor — registry=$REGISTRY interval=${INTERVAL}s"
main_loop
